### ISSUE TITLE
Add command-line interface

### ISSUE THREAD

**Issue by RaasAhsan** [PacketFire/gemini#10]
to start with:
- version
- help

**Comment by JosephMoniz** [comment]
Theres a lot of really good options we have available. I've had success with `argparse` in the pass and it's pretty magical stuff. I really want to use [click](https://click.palletsprojects.com/en/7.x/) though. It's super clean, very similar to Flask and doesn't require us writing a bunch of wiring like we'd have to artisanally design if we used `argparse`

**Comment by RaasAhsan** [comment]
click is also a requirement via pip-tools and flask already
