### ISSUE TITLE
Choose a Python HTTP server

### ISSUE THREAD

**Issue by RaasAhsan** [PacketFire/gemini#19]
For the Gemini master. It will be used both as an interface for clients to interact with their Gemini cluster and as a way for Gemini nodes to interact with the Gemini master (heartbeat/ping/pulling jobs). It can possibly be used for the Gemini nodes as well if there is any reason we want a server running for them.

- Django
- Flask
- Pyramid
- ???

**Comment by bramz** [comment]
cherrypy
fapws

**Comment by sabinprj** [comment]
I vote for Flask.

**Comment by jahan-addison** [comment]
flask.

**Comment by bramz** [comment]
oh we voting.. i vote for pyramid

**Comment by JosephMoniz** [comment]
Flask

**Comment by RaasAhsan** [comment]
got a lot of votes for flask both in this issue and outside -- will make a PR to add it in

**Comment by JosephMoniz** [comment]
Resolved by https://github.com/PacketFire/gemini/pull/22
