### ISSUE TITLE
Data store for Gemini master

### ISSUE THREAD

**Issue by RaasAhsan** [PacketFire/gemini#5]
We need to persist data about what is currently scheduled

- etcd
- consul

**Comment by RaasAhsan** [comment]
etcd looks like a solid choice

**Comment by bramz** [comment]
etcd

**Comment by RaasAhsan** [comment]
Going with consul, it'll help us store cluster state, service discovery for Gemini cluster, and service discovery for applications deployed inside Gemini.

will make a PR to add this

**Comment by RaasAhsan** [comment]
we using consul
